In [78]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
import numpy as np


In [50]:
#THIS IS A VARIABLE
zero=tf.Variable(0)

In [51]:
#constant
one=tf.constant(1)

In [52]:
new_value=tf.add(zero,one)

In [53]:
#variable value can be changed
update=tf.assign(zero,new_value)

In [58]:
#whwnever using variables ...use theis 3 below lines

init_op=tf.global_variables_initializer()
#initialie al variables

In [59]:

sess=tf.Session() #to close session....  sess.close()

In [60]:
#initialize variables
sess.run(init_op)

In [61]:
print(sess.run(zero))

0


In [63]:
for _ in range(5):
    sess.run(update)
    print(sess.run(zero))

1
2
3
4
5


In [64]:
#stringoperation

In [65]:
h=tf.constant("hello")

In [66]:
w=tf.constant("world")

In [67]:
hw=tf.add(h,w)

In [69]:
print(sess.run(hw))

b'helloworld'


In [70]:
#placeholder

In [93]:
a=tf.placeholder(tf.float32)

In [94]:
b=a*2

In [101]:
#feeding placeholder with scalar
result=sess.run(b,feed_dict={a:3})#feed_dict is var name
#result=sess.run(b,{a:3})
print(result)

6.0


In [102]:
#feeding a placehoder with rank 1
result=sess.run(b,feed_dict={a:[3,4,5]})

In [103]:
print(result)

[ 6.  8. 10.]


In [108]:
with tf.Session() as sess:
    result=sess.run(h+w)
    print(result)
    
    #all lises of only this block executed ith the session
    #not any other requirement of closing session sepraely

b'helloworld'


In [79]:
matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype = 'int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype = 'int32')

In [80]:

print (matrix1)
print (matrix2)

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [81]:

matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)
matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1,matrix2)

In [82]:
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype = 'float32')
print (matrix_3)

[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]


In [83]:
matrix_det = tf.matrix_determinant(matrix_3)


In [92]:
result1 = sess.run(matrix_product)
result2 = sess.run(matrix_sum)
result3 = sess.run(matrix_det)

In [89]:
print (result1)



[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [90]:
print (result2)

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [91]:
print (result3)

55.999992
